micronaut:
  application:
    name: bid
r2dbc:
  datasources:
    default:
      url: r2dbc:mariadb://localhost:3306/bidbattle
      username: bidbattle
      password: bidbattle
      schema-generate: CREATE_DROP
      dialect: MYSQL
